[package]
name = "oberon"
version = "0.1.0"
edition = "2021"
rust-version = "1.68.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.22.3"
structopt = "0.3.26"

[build-dependencies]
cmake = "0.1.49"
